FROM --platform=$BUILDPLATFORM openreserveio/base:latest
MAINTAINER mzero@openreserve.io

LABEL org.opencontainers.image.source=https://github.com/openreserveio/dwn/docs/operations/api
LABEL org.opencontainers.image.description="OpenReserve DWN API Container Image"
LABEL org.opencontainers.image.licenses="Apache 2.0"

EXPOSE 8080

VOLUME /etc/dwn
VOLUME /opt/dwn

CMD ["dwn", "api"]