FROM --platform=$BUILDPLATFORM ghcr.io/openreserveio/base:latest
MAINTAINER mzero@openreserve.io

LABEL org.opencontainers.image.source=https://github.com/openreserveio/dwn/docs/operations/collsvc
LABEL org.opencontainers.image.description="OpenReserve DWN Collection Service Container Image"
LABEL org.opencontainers.image.licenses="Apache 2.0"

EXPOSE 9001

VOLUME /etc/dwn
VOLUME /opt/dwn

CMD ["dwn", "collsvc"]