apiVersion: v1
kind: Service
metadata:
  name: eventsqueue-service
spec:
  selector:
    component: eventsqueue
  ports:
    - protocol: TCP
      port: 4222
      targetPort: eq-port
    - protocol: TCP
      port: 8222
      targetPort: eq-http-port