apiVersion: v1
kind: Service
metadata:
  name: otelcoll-service
spec:
  selector:
    component: otelcoll
  ports:
    - protocol: TCP
      port: 4317
      targetPort: oc-grpc-port
    - protocol: TCP
      port: 4318
      targetPort: oc-http-port
    - protocol: TCP
      port: 9464
      targetPort: oc-t1-port
    - protocol: TCP
      port: 8888
      targetPort: oc-t2-port
