apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: dwn
    component: api_deployment
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      component: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: dwn-api
        image: ghcr.io/openreserveio/api:latest
        ports:
          - containerPort: 8080
            name: dwnapi-port
        env:
          - name: "DWN_API.LISTENADDRESS"
            value: "0.0.0.0"
          - name: "DWN_API.LISTENPORT"
            value: "8080"
          - name: "DWN_RECORDSVC.EXTERNALADDRESS"
            value: "{{ .Release.Name }}-recordsvc"
          - name: "DWN_RECORDSVC.EXTERNALPORT"
            value: "9001"
          - name: "DWN_HOOKSVC.EXTERNALADDRESS"
            value: "{{ .Release.Name }}-hooksvc"
          - name: "DWN_HOOKSVC.EXTERNALPORT"
            value: "9003"
          - name: "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT"
            value: "http://{{ .Release.Name }}-otelcoll:4318/v1/traces"
          - name: "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT"
            value: "http://{{ .Release.Name }}-otelcoll:4318/v1/metrics"
        imagePullPolicy: Always
