apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-eventsqueue
spec:
  selector:
    component: eventsqueue
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: nats-client
      protocol: TCP
      port: 4222
      targetPort: eq-port
    - name: nats-mgmt
      protocol: TCP
      port: 8222
      targetPort: eq-http-port