apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-recordsvc
  labels:
    app: dwn
    component: recordsvc_deployment
spec:
  replicas: {{ .Values.recordsvc.replicaCount }}
  selector:
    matchLabels:
      component: recordsvc
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: recordsvc
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: dwn-recordsvc
        image: ghcr.io/openreserveio/recordsvc:latest
        ports:
          - containerPort: 9001
            name: dwnrcsvc-port
        env:
          - name: "DWN_RECORDSVC.LISTENPORT"
            value: "9001"
          - name: "DWN_RECORDSVC.DOCDBCONNECTIONURI"
            value: "mongodb://openreserveuser:openreservepass@{{ .Release.Name }}-mongodb:27017"
          - name: "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT"
            value: "http://{{ .Release.Name }}-otelcoll:4318/v1/traces"
          - name: "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT"
            value: "http://{{ .Release.Name }}-otelcoll:4318/v1/metrics"
        imagePullPolicy: Always
