apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-recordsvc
spec:
  selector:
    component: recordsvc
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 9001
      targetPort: dwnrecordsvc-port