version: "3.9"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"


volumes:
  mysql_data:
      driver: local
  documentdb_data:
      driver: local
  localstack_data:
      driver: local
    
services:

  # ********************
  # Telemetry Components
  # ********************
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    command:
      - "--memory.max-traces"
      - "10000"
      - "--query.base-path"
      - "/jaeger/ui"
      - "--prometheus.server-url"
      - "http://prometheus:9090"
    deploy:
      resources:
        limits:
          memory: 275M
    restart: always
    ports:
      - "8005:16686"                          # Jaeger UI
      - "4317"                           # OTLP gRPC default port
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
    logging: *logging

  # Grafana
  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    logging: *logging

  # OpenTelemetry Collector
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.61.0
    container_name: otelcol
    deploy:
      resources:
        limits:
          memory: 100M
    restart: always
    command: [ "--config=/etc/otelcol-config.yml", "--config=/etc/otelcol-config-extras.yml" ]
    volumes:
      - ./otelcol-config.yml:/etc/otelcol-config.yml
      - ./otelcol-config-extras.yml:/etc/otelcol-config-extras.yml
    ports:
      - "4317:4317"     # OTLP over gRPC receiver
      - "4318:4318"     # OTLP over HTTP receiver
      - "9464"          # Prometheus exporter
      - "8888"          # metrics endpoint
    depends_on:
      - jaeger
    logging: *logging

  # Prometheus
  prometheus:
    image: quay.io/prometheus/prometheus:v2.34.0
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    ports:
      - "9090:9090"
    logging: *logging

  # Common Infrastructure Components
  eventsqueue:
    image: "nats"
    ports:
      - "4222:4222"
      - "8222:8222"
  docdb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=openreserveuser"
      - "MONGO_INITDB_ROOT_PASSWORD=openreservepass"
    volumes:
      - "documentdb_data:/data/db"
  
  localstack:
    image: "localstack/localstack"
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - PERSISTENCE=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # This allows for data to not be persisted on new runs
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]
  
  
  # SSI Service Components
  # ssiservice:
  #   image: "openreserveio/ssi-service:latest"
  #   ports:
  #     - "9080:3000"
  #   environment:
  #     - JAEGER_HTTP_URL=http://jaeger:4317/api/traces
  #   depends_on:
  #     - jaeger
  #     - redis
  #   volumes:
  #     - ./ssiservice-config.toml:/app/config/config.toml

  # ssiservice-swagger:
  #   image: "openreserveio/ssi-service-swagger:latest"
  #   ports:
  #     - "9081:8080"
  #   volumes:
  #     - ./ssiservice-swagger.yaml:/app/swagger.yaml
  #   command: ["serve", "/app/swagger.yaml", "--no-open", "--port", "8080"]

  # ssiservice-ui:
  #   image: "openreserveio/ssi-service-gui:latest"
  #   ports:
  #     - "9082:8501"
  #   depends_on:
  #     - ssiservice
    

  # DWN Components
  hooksvc:
    image: "openreserveio/hooksvc:latest"
    build:
      context: "../../../go"
      dockerfile: "applications/pkg/docker/Dockerfile-hooksvc"
      tags:
        - "openreserveio/hooksvc"
    ports:
      - "9003:9003"
    environment:
      - "DWN_HOOKSVC.DOCDBCONNECTIONURI=mongodb://openreserveuser:openreservepass@docdb:27017"
      - "DWN_HOOKSVC.LISTENPORT=9003"
      - "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otelcol:4318/v1/traces"
      - "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otelcol:4318/v1/metrics"
  recordsvc:
    image: "openreserveio/recordsvc:latest"
    build:
      context: "../../../go"
      dockerfile: "applications/pkg/docker/Dockerfile-recordsvc"
      tags:
        - "openreserveio/recordsvc"
    ports:
      - "9001:9001"
    environment:
      - "DWN_RECORDSVC.DOCDBCONNECTIONURI=mongodb://openreserveuser:openreservepass@docdb:27017"
      - "DWN_RECORDSVC.LISTENPORT=9001"
      - "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otelcol:4318/v1/traces"
      - "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otelcol:4318/v1/metrics"
  api:
    image: "openreserveio/api:latest"
    build:
      context: "../../../go"
      dockerfile: "applications/pkg/docker/Dockerfile-api"
      tags:
        - "openreserveio/api"
    ports:
      - "8080:8080"
    environment:
      - "DWN_API.LISTENPORT=8080"
      - "DWN_RECORDSVC.EXTERNALADDRESS=recordsvc"
      - "DWN_RECORDSVC.EXTERNALPORT=9001"
      - "DWN_HOOKSVC.EXTERNALADDRESS=hooksvc"
      - "DWN_HOOKSVC.EXTERNALPORT=9003"
      # - "OPEN_TELEMETRY_COLLECTOR_URL=http://otelcol:4318/v1/traces"
      - "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otelcol:4318/v1/traces"
      # - "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otelcol:4317"
  