version: "3.9"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"


volumes:
  mysql_data:
      driver: local
  documentdb_data:
      driver: local
  localstack_data:
      driver: local
    
services:

  # ********************
  # Telemetry Components
  # ********************
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    command:
      - "--memory.max-traces"
      - "10000"
      - "--query.base-path"
      - "/jaeger/ui"
      - "--prometheus.server-url"
      - "http://prometheus:9090"
    deploy:
      resources:
        limits:
          memory: 275M
    restart: always
    ports:
      - "8005:16686"                          # Jaeger UI
      - "4317"                           # OTLP gRPC default port
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
    logging: *logging

  # Grafana
  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    logging: *logging

  # OpenTelemetry Collector
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.61.0
    container_name: otelcol
    deploy:
      resources:
        limits:
          memory: 100M
    restart: always
    command: [ "--config=/etc/otelcol-config.yml", "--config=/etc/otelcol-config-extras.yml" ]
    volumes:
      - ./otelcol-config.yml:/etc/otelcol-config.yml
      - ./otelcol-config-extras.yml:/etc/otelcol-config-extras.yml
    ports:
      - "4317:4317"     # OTLP over gRPC receiver
      - "4318:4318"     # OTLP over HTTP receiver
      - "9464"          # Prometheus exporter
      - "8888"          # metrics endpoint
    depends_on:
      - jaeger
    logging: *logging

  # Prometheus
  prometheus:
    image: quay.io/prometheus/prometheus:v2.34.0
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    ports:
      - "9090:9090"
    logging: *logging

  # Common Infrastructure Components
  eventsqueue:
    image: "nats"
    ports:
      - "4222:4222"
      - "8222:8222"
  docdb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=openreserveuser"
      - "MONGO_INITDB_ROOT_PASSWORD=openreservepass"
    volumes:
      - "documentdb_data:/data/db"
  localstack:
    image: "localstack/localstack"
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - PERSISTENCE=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  # DWN Components
  collsvc:
    image: "openreserveio/collsvc:latest"
    build:
      context: "../../../go"
      dockerfile: "applications/pkg/docker/Dockerfile-collsvc"
      tags:
        - "openreserveio/collsvc"
    ports:
      - "9001:9001"
    environment:
      - "DWN_COLLSVC.DOCDBCONNECTIONURI=mongodb://openreserveuser:openreservepass@docdb:27017"
      - "DWN_COLLSVC.LISTENPORT=9001"
      - "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otelcol:4318/v1/traces"
      - "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otelcol:4318/v1/metrics"
  api:
    image: "openreserveio/api:latest"
    build:
      context: "../../../go"
      dockerfile: "applications/pkg/docker/Dockerfile-api"
      tags:
        - "openreserveio/api"
    ports:
      - "8080:8080"
    environment:
      - "DWN_API.LISTENPORT=8080"
      - "DWN_COLLSVC.EXTERNALADDRESS=collsvc"
      - "DWN_COLLSVC.EXTERNALPORT=9001"
      # - "OPEN_TELEMETRY_COLLECTOR_URL=http://otelcol:4318/v1/traces"
      - "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otelcol:4318/v1/traces"
      # - "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otelcol:4317"
  